name = "jianxing"
compatibility_date = "2026-07-22"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "FILES"
bucket_name = "jianxing-files"

[[d1_databases]]
binding = "DB"
database_name = "jianxing-app"
database_id = "633c13ef-9220-47dc-b920-589eb5588a86"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "jianxing-passages"
